spring.application.name=appsa

# Propriedades do Banco de Dados
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Propriedades da JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Servidor
server.port=${SERVER_PORT}

# Nome do arquivo de log
logging.file.name=logs/app.log

# OU diretório de logs
logging.file.path=logs

# Nível global
logging.level.root=INFO

# Nível por pacote
logging.level.com.smart.appsa=DEBUG