spring.application.name=appsa

# Propriedades do Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3306/bancadasmart
spring.datasource.username=root
spring.datasource.password=12345

# Propriedades da JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect



# Propriedades do Server
server.port=8088